# Generated by Django 3.1.8 on 2021-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210601_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='videoId',
            field=models.IntegerField(default=None),
        ),
    ]
