# Generated by Django 3.1.8 on 2021-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='videoId',
            field=models.CharField(max_length=300),
        ),
    ]
